# TranscriptionAedes-core-promoter-motifs

# Steps
  # 01_prepare_promoter_regions.R
  # 02_search_motifs.sh
  # 03_plot_motifs.R


####################################################################################################
# 02_search_motifs.sh
#
# Language: Bash / Unix
#
# Aim:
#   Search for INR, TATA box, and DPE motifs in old/current annotated TSS and PRO-seq updated TSN regions
#
# Motifs
#   INR: TCAKTY
#   TATA: TATAWAW
#   DPE: RGWYV
#
# Input:
#   BED files generated by 01_prepare_promoter_regions.R
#
# Output:
#   Motif position files, for each strand, for either TSS/TSN, and for each motif
####################################################################################################

#!/bin/bash -l
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -pe smp 8


# Directories
BASE_DIR="/home/femkevh/PROseq/Aag2"
MOTIF_DIR="${BASE_DIR}/tss/core_promoter_motifs"
GENOME="/AaegL5/Chromosome_fasta/Aedes-aegypti-LVP_AGWG_CHROMOSOMES_AaegL5.fa"

cd "${MOTIF_DIR}" 


####################################################
# INR motif search
####################################################

# Plus, old TSS
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_INR_oldTSS_plus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o 'TCAGTC\|TCAGTT\|TCATTC\|TCATTT' | awk -F: -v name="${name}" '{OFS="\t"; print $1-20, name, $2}' >> motifs_INR_oldTSS_plus.txt
done < oldTSS_INR_regions_plus.bed

# Plus, new TSN
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_INR_newTSS_plus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o 'TCAGTC\|TCAGTT\|TCATTC\|TCATTT' | awk -F: -v name="${name}" '{OFS="\t"; print $1-20, name, $2}' >> motifs_INR_newTSS_plus.txt
done < newTSS_INR_regions_plus.bed

# Minus, old TSS
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_INR_oldTSS_minus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o 'GACTGA\|AACTGA\|GAATGA\|AAATGA' | awk -F: -v name="${name}" '{OFS="\t"; print 20-$1-6, name, $2}' >> motifs_INR_oldTSS_minus.txt
done < oldTSS_INR_regions_minus.bed

# Minus, new TSN
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_INR_newTSS_minus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o 'GACTGA\|AACTGA\|GAATGA\|AAATGA' | awk -F: -v name="${name}" '{OFS="\t"; print 20-$1-6, name, $2}' >> motifs_INR_newTSS_minus.txt
done < newTSS_INR_regions_minus.bed


####################################################
# TATA box motif search
####################################################

# Plus, old TSS
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_TATA_oldTSS_plus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o 'TATATAT\|TATAAAA\|TATATAA\|TATAAAT' | awk -F: -v name="${name}" '{OFS="\t"; print $1-60, name, $2}' >> motifs_TATA_oldTSS_plus.txt
done < oldTSS_TATA_regions_plus.bed

# Plus, new TSN
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_TATA_newTSS_plus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o 'TATATAT\|TATAAAA\|TATATAA\|TATAAAT' | awk -F: -v name="${name}" '{OFS="\t"; print $1-60, name, $2}' >> motifs_TATA_newTSS_plus.txt
done < newTSS_TATA_regions_plus.bed

# Minus, old TSS
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_TATA_oldTSS_minus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o 'ATATATA\|TTTTATA\|TTATATA\|ATTTATA' | awk -F: -v name="${name}" '{OFS="\t"; print -$1, name, $2}' >> motifs_TATA_oldTSS_minus.txt
done < oldTSS_TATA_regions_minus.bed

# Minus, new TSN
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_TATA_newTSS_minus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o 'ATATATA\|TTTTATA\|TTATATA\|ATTTATA' | awk -F: -v name="${name}" '{OFS="\t"; print -$1, name, $2}' >> motifs_TATA_newTSS_minus.txt
done < newTSS_TATA_regions_minus.bed


####################################################
# DPE motif search
####################################################

# Plus, old TSS
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_DPE_oldTSS_plus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o '[AG][G][AT][CT][ACG]' | awk -F: -v name="${name}" '{OFS="\t"; print $1+20, name, $2}' >> motifs_DPE_oldTSS_plus.txt
done < oldTSS_DPE_regions_plus.bed

# Plus, new TSN
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_DPE_newTSS_plus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o '[AG][G][AT][CT][ACG]' | awk -F: -v name="${name}" '{OFS="\t"; print $1+20, name, $2}' >> motifs_DPE_newTSS_plus.txt
done < newTSS_DPE_regions_plus.bed

# Minus, old TSS
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_DPE_oldTSS_minus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o '[TGC][GA][TA][C][TC]' | awk -F: -v name="${name}" '{OFS="\t"; print 40-$1-5, name, $2}' >> motifs_DPE_oldTSS_minus.txt
done < oldTSS_DPE_regions_minus.bed

# Minus, new TSN
echo -e "motif_position\tgenename_isoform\tmotif_sequence" > motifs_DPE_newTSS_minus.txt
while read -r chrom start end name
do
    sequence=$(bedtools getfasta -fi "${GENOME}" -bed <(echo -e "${chrom}\t${start}\t${end}") -fo /dev/stdout | tail -n +2 | tr -d '\n')
    echo "${sequence}" | grep -b -o '[TGC][GA][TA][C][TC]' | awk -F: -v name="${name}" '{OFS="\t"; print 40-$1-5, name, $2}' >> motifs_DPE_newTSS_minus.txt
done < newTSS_DPE_regions_minus.bed
